---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: dkube-dockerhub-secret
type: kubernetes.io/dockerconfigjson
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkubex-proxy-ui
  labels:
    app: dkubex-proxy-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkubex-proxy-ui
  template:
    metadata:
      labels:
        app: dkubex-proxy-ui
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/dkubex-proxy-ui:dkubex
        imagePullPolicy: Always
        env:
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              key: anonKey
              name: dkubex-supabase-jwt
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: dkubex-supabase-jwt
        - name: SUPABASE_URL
          value: http://dkubex-supabase-kong:8000
        - name: DATABASE_URL
          value: postgresql://postgres:example123456@dkubex-supabase-db:5432/postgres

---

apiVersion: v1
kind: Service
metadata:
  name: dkubex-proxy-ui
spec:
  type: NodePort
  selector:
    app: dkubex-proxy-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: dkubex-proxy-backend
  labels:
    app: dkubex-proxy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dkubex-proxy-backend
  template:
    metadata:
      labels:
        app: dkubex-proxy-backend
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/llmproxy:dkubex
        imagePullPolicy: Always
        env:
        - name: SUPABASE_SERVICE_ROLEKEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: dkubex-supabase-jwt
        - name: SUPABASE_URL
          value: http://dkubex-supabase-kong:8000
        - name: SGPT_ADMIN_PASSWORD
          value: "{{ .Values.sgptAdminPassword }}"
        - name: SGPT_ADMIN_USER
          value: "{{ .Values.sgptAdminUser }}"
        - name: SGPT_OPENAI_KEY
          value: "{{ .Values.sgptOpenaiKey }}"
        startupProbe:
          tcpSocket:
            port: 8899
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 15

---

apiVersion: v1
kind: Service
metadata:
  name: dkubex-proxy-backend
spec:
  type: NodePort
  selector:
    app: dkubex-proxy-backend
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 8899

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-ui
  labels:
    app: chatbot-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-ui
  template:
    metadata:
      labels:
        app: chatbot-ui
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/chatbot-ui:altos
        imagePullPolicy: Always
        env:
        - name: OPENAI_API_HOST
          value: http://dkubex-proxy-backend:3005
---

apiVersion: v1
kind: Service
metadata:
  name: chatbot-ui
spec:
  type: NodePort
  selector:
    app: chatbot-ui
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3000
---

