---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: dkube-dockerhub-secret
type: kubernetes.io/dockerconfigjson
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: securegpt-fe
  labels:
    app: securegpt-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securegpt-fe
  template:
    metadata:
      labels:
        app: securegpt-fe
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/securegpt-fe:dkubex
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.supabase.db.secretName }}
        env:
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              key: anonKey
              name: supabase-jwt
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: supabase-jwt
        - name: SUPABASE_URL
          value: http://supabase-kong:8000
        - name: DATABASE_URL
          value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)

---

apiVersion: v1
kind: Service
metadata:
  name: securegpt-fe
spec:
  type: NodePort
  selector:
    app: securegpt-fe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: securegpt-be
  labels:
    app: securegpt-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securegpt-be
  template:
    metadata:
      labels:
        app: securegpt-be
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/securegpt-be:dkubex
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.supabase.db.secretName }}
        env:
        - name: SUPABASE_SERVICE_ROLEKEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: supabase-jwt
        - name: SECURECHAT_APPKEY
          valueFrom:
            secretKeyRef:
              key: appkey
              name: securechat-appkey
        - name: SUPABASE_URL
          value: http://supabase-kong:8000
        - name: SGPT_ADMIN_PASSWORD
          value: "{{ .Values.sgptAdminPassword }}"
        - name: SGPT_ADMIN_USER
          value: "{{ .Values.sgptAdminUser }}"
        - name: SGPT_OPENAI_KEY
          value: "{{ .Values.sgptOpenaiKey }}"
        startupProbe:
          tcpSocket:
            port: 8899
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 15

---

apiVersion: v1
kind: Service
metadata:
  name: securegpt-be
spec:
  type: NodePort
  selector:
    app: securegpt-be
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 8899

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: securechat
  labels:
    app: securechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securechat
  template:
    metadata:
      labels:
        app: securechat
    spec:
      imagePullSecrets:
      - name: dkube-dockerhub-secret
      containers:
      - name: main
        image: ocdr/securechat:altos
        imagePullPolicy: Always
        env:
        - name: OPENAI_API_HOST
          value: http://securegpt-be:3005
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: appkey
              name: securechat-appkey

---

apiVersion: v1
kind: Service
metadata:
  name: securechat
spec:
  type: NodePort
  selector:
    app: securechat
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3000
---

apiVersion: v1
kind: Secret
metadata:
  name: "securechat-appkey"
type: Opaque
data:
  appkey: {{ randAlphaNum 32 | lower | b64enc | quote }}

---

