{{- if not .Values.global.db.externalDB }}
{{- if .Values.global.db.internal.nfs.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: securegpt
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 100Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: securegpt
    namespace: {{ .Release.Namespace }}
  nfs:
    path: /
    server: {{ .Values.global.db.internal.nfs.server}}
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
{{- end }}
{{- end }}
