{{- if not .Values.global.db.externalDB }}
{{- if .Values.global.db.internal.nfs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: securegpt
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100G
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: securegpt
{{- end }}
{{- end }}
