global:
  db:
    wipedata: false
    externalDB: false
    external:
      dbUser: ""
      dbPassword: ""
      dbHost: ""
      dbPort: ""
      dbName: ""
      dbSSL: false
    internal:
      dbUser: ""
      dbPassword: ""
      nfs:
        enabled: false
        server: ""
        path: ""

sllmAdminUser: "admin@dkubex.ai"
sllmAdminPassword: ""
sllmOpenaiKey: ""

imageCredentials:
  registry: "https://index.docker.io/v1/"
  username: ""
  password: ""

ingress:
  oauth:
    enabled: false
  className: "nginx"
  # For acceting all the hosts, leave it empty string.
  host: ""

supabase:
  jwt:
    secretName: "supabase-jwt"
  
  smtp:
    secretName: "supabase-smtp"
  
  db:
    enabled: true
    image:
      repository: docker.io/postgres
      tag: 15.2
    imagePullSecrets:
    - name: securellm-dockerhub-secret
    secretName: "supabase-db"
    persistence:
      enabled: false
    storage:
        mountPath: /var/lib/postgresql/data
        size: 20Gi
        storageClass: standard
        annotations:
          helm.sh/resource-policy: "keep"
  
  auth:
    image:
      repository: supabase/gotrue
      tag: v2.82.4
    environment:
      DB_SSL: prefer
      GOTRUE_API_HOST: "0.0.0.0"
      GOTRUE_API_PORT: "9999"
      GOTRUE_SITE_URL: http://studio.localhost
      GOTRUE_URI_ALLOW_LIST: "*"
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_EXP: "3600"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
      GOTRUE_SMTP_HOST: "smtp.example.com"
      GOTRUE_SMTP_PORT: "587"
      GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
      GOTRUE_EXTERNAL_PHONE_ENABLED: "false"
      GOTRUE_SMS_AUTOCONFIRM: "false"
      GOTRUE_MAILER_URLPATHS_INVITE: "http://localhost:32534/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: "http://localhost:32534/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_RECOVERY: "http://localhost:32534/auth/v1/verify"
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: "http://localhost:32534/auth/v1/verify"
  
  rest:
    image:
      repository: postgrest/postgrest
      tag: v10.1.2
    environment:
      DB_SSL: prefer
      PGRST_DB_SCHEMA: public,storage
      PGRST_DB_ANON_ROLE: anon
      PGRST_DB_USE_LEGACY_GUCS: "false"
  
  kong:
    service:
      type: ClusterIP
    image:
      repository: kong
      tag: 2.8.1
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl
      KONG_LOG_LEVEL: debug
