apiVersion: batch/v1
kind: Job
metadata:
  name: "dkubex-installer"
  namespace: {{ .Release.Namespace }}
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "dkubex-installer"
    spec:
      hostPID: true
      restartPolicy: Never
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: dkubex-installer
        image: dkubex123/d3x-installer:{{ .Values.image_tag }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
       
        command: ["/bin/sh", 
        "-c", 
        "dxm install-dkubex  /etc/config/config.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: dkubex-config
        
      serviceAccountName: dkubex-deployer-sa
