apiVersion: batch/v1
kind: Job
metadata:
  name: "infl-installer"
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "3"
spec:
  backoffLimit: 0
  template:
    metadata:
      name: "infl-installer"
    spec:
      hostPID: true
      restartPolicy: Never
      imagePullSecrets:
      - name: dockerhub-secret
      containers:
      - name: infl-installer
        image: dkubex123/ops-installer:{{ .Values.image_tag }}
        imagePullPolicy: Always
        securityContext:
          privileged: true
       
        command: ["/bin/sh", 
        "-c", 
        "dxm install-dkubex  /etc/config/config.yaml"]
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
        - name: config-volume
          configMap:
            name: infl-config
        
      serviceAccountName: infl-deployer-sa
