apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: default
  namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson:  {{ template "imagePullSecret" . }}
type: kubernetes.io/dockerconfigjson
