---
apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  name: securellm-dockerhub-secret
type: kubernetes.io/dockerconfigjson
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: securellm-fe
  labels:
    app: securellm-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securellm-fe
  template:
    metadata:
      labels:
        app: securellm-fe
    spec:
      imagePullSecrets:
      - name: securellm-dockerhub-secret
      containers:
      - name: main
        image: dkubex123/securellm-fe:0.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.supabase.db.secretName }}
        env:
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              key: anonKey
              name: supabase-jwt
        - name: SUPABASE_SERVICE_KEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: supabase-jwt
        - name: SUPABASE_URL
          value: http://supabase-kong:8000
        - name: DATABASE_URL
          {{- define "sslmode" }}
          {{- if and .Values.global.db.externalDB .Values.global.db.external.dbSSL }}no-verify{{ else }}disable{{ end }}
          {{- end }}
          value: postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?sslmode={{ include "sslmode" . }}
        - name: SLLM_USER
          value: "{{ .Values.sllmUsername }}"
        - name: SLLM_USER_PASSWORD
          value: "{{ .Values.sllmUserPassword }}"

---

apiVersion: v1
kind: Service
metadata:
  name: securellm-fe
spec:
  type: ClusterIP
  selector:
    app: securellm-fe
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: securellm-be
  labels:
    app: securellm-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securellm-be
  template:
    metadata:
      labels:
        app: securellm-be
    spec:
      imagePullSecrets:
      - name: securellm-dockerhub-secret
      initContainers:
      - name: init
        command: ["/opt/db/migrate.sh"]
        image: dkubex123/securellm-be:0.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.supabase.db.secretName }}
      containers:
      - name: main
        image: dkubex123/securellm-be:0.2
        imagePullPolicy: Always
        envFrom:
        - secretRef:
            name: {{ .Values.supabase.db.secretName }}
        env:
        - name: SUPABASE_SERVICE_ROLEKEY
          valueFrom:
            secretKeyRef:
              key: serviceKey
              name: supabase-jwt
        - name: SECURECHAT_APPKEY
          valueFrom:
            secretKeyRef:
              key: appkey
              name: securechat-appkey
        - name: SUPABASE_URL
          value: http://supabase-kong:8000
        - name: SLLM_ADMIN_PASSWORD
          value: "{{ .Values.sllmAdminPassword }}"
        - name: SLLM_ADMIN_USER
          value: "{{ .Values.sllmAdminUser }}"
        - name: SLLM_OPENAI_KEY
          value: "{{ .Values.sllmOpenaiKey }}"
        - name: SLLM_USER
          value: "{{ .Values.sllmUsername }}"
        - name: SLLM_USER_PASSWORD
          value: "{{ .Values.sllmUserPassword }}"
        startupProbe:
          tcpSocket:
            port: 8899
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 15

---

apiVersion: v1
kind: Service
metadata:
  name: securellm-be
spec:
  type: ClusterIP
  selector:
    app: securellm-be
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 8899

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: securechat
  labels:
    app: securechat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: securechat
  template:
    metadata:
      labels:
        app: securechat
    spec:
      imagePullSecrets:
      - name: securellm-dockerhub-secret
      containers:
      - name: main
        image: dkubex123/securechat:altos
        imagePullPolicy: Always
        env:
        - name: OPENAI_API_HOST
          value: http://securellm-be:3005
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              key: appkey
              name: securechat-appkey

---

apiVersion: v1
kind: Service
metadata:
  name: securechat
spec:
  type: ClusterIP
  selector:
    app: securechat
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3000
---

apiVersion: v1
kind: Secret
metadata:
  name: "securechat-appkey"
type: Opaque
data:
  appkey: {{ randAlphaNum 32 | lower | b64enc | quote }}

---

