apiVersion: v1
data:
  anonKey: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV3b2dJQ0FnSW5KdmJHVWlPaUFpWVc1dmJpSXNDaUFnSUNBaWFYTnpJam9nSW5OMWNHRmlZWE5sSWl3S0lDQWdJQ0pwWVhRaU9pQXhOamMxTkRBd05EQXdMQW9nSUNBZ0ltVjRjQ0k2SURFNE16TXhOalk0TURBS2ZRLnp0dWlCemphVm9GSG1vbGpVWFdtbnVETjZRVTJXZ0pJQ2Vxd3l6eVpPODg=
  secret: YWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXoxMjM0NTY=
  serviceKey: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV3b2dJQ0FnSW5KdmJHVWlPaUFpYzJWeWRtbGpaVjl5YjJ4bElpd0tJQ0FnSUNKcGMzTWlPaUFpYzNWd1lXSmhjMlVpTEFvZ0lDQWdJbWxoZENJNklERTJOelUwTURBME1EQXNDaUFnSUNBaVpYaHdJam9nTVRnek16RTJOamd3TUFwOS5xTnNtWHp6NHRHN2VxSlBoMVk1OERidElsSkJhdXdwcXgzOVVGLU13TThr
kind: Secret
metadata:
  name: {{ .Values.jwt.secretName }}
---
apiVersion: v1
data:
  password: ZXhhbXBsZTEyMzQ1Ng==
  username: eW91ci1tYWlsQGV4YW1wbGUuY29t
kind: Secret
metadata:
  name: {{ .Values.smtp.secretName }}
---
apiVersion: v1
data:
{{- if .Release.IsUpgrade }}
  DB_PASSWORD: {{ (lookup "v1" "Secret" "securellm" .Values.db.secretName).data.DB_PASSWORD }}
{{- else }}
  DB_PASSWORD: {{ include "dbPassword" . | b64enc }}
{{- end }}
  DB_USER: {{ include "dbUser" . | b64enc }}
  DB_HOST: {{ include "dbHost" . | b64enc }}
  DB_PORT: {{ include "dbPort" . | b64enc }}
  DB_NAME: {{ include "dbName" . | b64enc }}
  DB_DRIVER: {{ "postgres" | b64enc }}
kind: Secret
metadata:
  name: {{ .Values.db.secretName }}
