# Default values for dkubex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
namespace: "infl"
image_tag: "infai"
admin_password: "inflectionai"
provider : "intel" # rancher

# Docker registry for installation
container_registry:
    # Format: registry/[repo]
    uri: "docker.io/dkubex123" #harbor URL

    # Container registry username
    username: "dkubex123"

    # Container registry password
    password: ""

# nfs or hostpath
storage_type: "nfs"
nfs:
    # true for creating internal nfs server
    create_server: true
    # specify host path for creating internal nfs
    storage_path: "/var/dkubex"
    # Specify storage class. If both storage_path and storage_class are specified,
    # storage_class takes precedence.
    storage_class: ""
    internal_nfs_node_selector:
        node_selector_key: "kubernetes.io/os"
        node_selector_value: "linux"
        taint : ""
    # Format: <server ip>:<path>
    nfs_server: "kubernetes:/"
    # specify nfs version supported are 4.1 and 4.0
    version: "4.1"
hostpath:
    # specify  host path 
    storage_path: "/var/dkubex"

# Format: dialect+driver://username:password@host:port/database
database_url: ""
image_pull_policy: "Always"

# gpu provider related settings
gpu_provider: intel #nvidia
intel:
  install: false
  habana_device_plugin: true
  runtime_class_crd: true
nvidia:
   install: false
   driver: false #install driver
   toolkit: false #install toolkit

# checkpoint storage information
production:
    namespace: ""
    checkpoints_pvc: ""

# domain name configuration
domain: ""

#enables Oauth for dkubex, user can configure this from admin ui after installation too 
auth:
    enabled: false
    provider: "github" #okta/github/azure/adfs/keycloak
    issuer_url: ""
    client_id: ""
    client_secret: ""
    redirect_url: "" #https://<IP/DOMAIN_NAME>:32443/oauth2/callback
    organisation: ""
    email_domain: "*"
    azure_tenant: "" #tenent id for azure ad
    realm: "" # realm for keycload
    allowed_role: "" #keycload allowed role name
    allowed_group: "" # keycload allowed group name

model_registry:
    replica_count : 1
    database_url: ""
    artifacts_destination: ""
    aws_access_key_id: ""
    aws_access_secret: ""

# inflai components/controllers will be scheduled onto control-plane nodes.
control_plane:
    node_selector: "kubernetes.io/os"
    node_selector_value: "linux, windows"
    node_taint: "" # by default tolerates all the taints, format: "key=value:effect" or "key:effect"
    enabled: false

packages:
    knative: false
    cert-manager: false
    kserve: false
    kourier: true

