{{- if .Values.auth.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "supabase.auth.fullname" . }}
  labels:
    {{- include "supabase.labels" . | nindent 4 }}
spec:
  {{- if not .Values.auth.autoscaling.enabled }}
  replicas: {{ .Values.auth.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "supabase.auth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.auth.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "supabase.auth.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.auth.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "supabase.auth.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.auth.podSecurityContext | nindent 8 }}
      initContainers:
        - name: init-db
          image: docker.io/bitnami/kubectl:1.25.9
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: {{ .Values.db.secretName }}
          command: ["/bin/bash", "-c"]
          args:
            - |
              set -e
              echo "Waiting for initial db migration, performed by securellm backend..."
              while true
              do
                  out=$(kubectl -n securellm get po -l app=securellm-be -ojsonpath='{.items[0].status.initContainerStatuses[0].state.terminated.exitCode}')
                  init_ctr_code=$(echo "$out" | tr -d '[:space:]')
                  if [[ "$init_ctr_code" == "" || $init_ctr_code -ne 0 ]]; then
                      sleep 5
                      continue
                  fi
                  break
              done
              echo "Done."
      containers:
        - name: {{ include "supabase.auth.name" $ }}
          securityContext:
            {{- toYaml .Values.auth.securityContext | nindent 12 }}
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          envFrom:
          - secretRef:
              name: {{ .Values.db.secretName }}
          env:
            {{- range $key, $value := .Values.auth.environment }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  name: {{ include "supabase.auth.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            - name: GOTRUE_DB_DATABASE_URL
              value: $(DB_DRIVER)://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)?search_path=auth&sslmode=$(DB_SSL)
            - name: GOTRUE_DB_DRIVER
              value: $(DB_DRIVER)
            - name: GOTRUE_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.jwt.secretName }}
                  key: secret
            - name: GOTRUE_SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: username
            - name: GOTRUE_SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.smtp.secretName }}
                  key: password
          ports:
            - name: http
              containerPort: 9999
              protocol: TCP
          {{- with .Values.auth.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.auth.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.auth.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.auth.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
